# "EXAMPLES OF numpy MODULE"

# STARTING OF LECTURE-25:

In [50]:
import numpy
#.array() Fn.
# creating array from list
arr1=numpy.array([1,2,3,4,5,6,7,8])
print(arr1)                 

[1 2 3 4 5 6 7 8]


In [1]:
import numpy as np
# creating array from tuple
arr2=np.array((1,2,3,4))
print(arr2)

[1 2 3 4]


In [68]:
# continue from above....
# finding Maximum and Minimum for 1D array
# And indexValues of both
# sum of array
print(arr2.max())
print("index of maxValue: ",arr2.argmax())
print(arr2.min())
print("index of minValue: ",arr2.argmin())
print("Sum of array elements: ", arr2.sum())

4
index of maxValue:  3
1
index of minValue:  0
Sum of array elements:  10


In [51]:
# using arr1
# access through indexing
# same as list for 1D array
print(arr1[2])
print(arr1[0])

3
1


In [52]:
# using arr1
# slicing of 1D array
# same as list for 1D array
print(arr1[:])
print(arr1[:2])
print(arr1[4:])
print(arr1[-4:-1])

[1 2 3 4 5 6 7 8]
[1 2]
[5 6 7 8]
[5 6 7]


In [54]:
# array's element are mutable or we can change the values in array
x=arr1[2:6]=50
print(x)
print(arr1)

50
[ 1  2 50 50 50 50  7  8]


In [58]:
# coping an array
y=arr1.copy()
print(y)
z=y[4:7]=80
print(z)
print(y)

[ 1  2 50 50 50 50  7  8]
80
[ 1  2 50 50 80 80 80  8]


In [64]:
# Conditional selection of elements
print(y)
# in case of returning result through indexes
print(y > 40)
# in case of returning result directly
print(y[y > 40])
# another condition
print(y[y%4 == 0])

[ 1  2 50 50 80 80 80  8]
[False False  True  True  True  True  True False]
[50 50 80 80 80]
[80 80 80  8]


In [74]:
# Operation on elements of an array
print(np.sin(y))
print(np.log(y))
print(np.max(y))
print(np.min(y))

[ 0.84147098  0.90929743 -0.26237485 -0.26237485 -0.99388865 -0.99388865
 -0.99388865  0.98935825]
[0.         0.69314718 3.91202301 3.91202301 4.38202663 4.38202663
 4.38202663 2.07944154]
80
1


In [79]:
# common between two arrays
a = np.array([1,1,2,3,4,5,6])
b = np.array([0,2,1,3,4,8,9])
print("Common elements between both arrays :\n",np.intersect1d(a,b))

Common elements between both arrays :
 [1 2 3 4]


In [20]:
# types
print(type(arr1))    #Module imported already 1st line & keep short as 'np' in 2nd line .
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
# 2D array
arr2D=np.array([[1,2,3], [4,5,6]])     #Module imported already 1st line & keep short as 'np' in 2nd line .
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [69]:
# continue from above....
# finding Maximum and Minimum for 2D array
print(arr2D.max())
print(arr2D.min())
print("index of minValue: ",arr2D.argmin())
print("Sum of array elements: ", arr2D.sum())

6
1
index of minValue:  0
Sum of array elements:  21


In [65]:
# access through indexing of 2D array
print(arr2D[0,2])
print(arr2D[1,0])

3
4


In [67]:
# slicing of 2D array
print(arr2D[:1,:2],"\n")
print(arr2D[:,1:])

[[1 2]] 

[[2 3]
 [5 6]]


In [78]:
# common between two arrays
c=np.array([[1,2],[3,4]])
print(c)
d=np.array([[5,6],[3,7]])
print(d)
print("Common elements between both arrays :\n",np.intersect1d(c,d))

[[1 2]
 [3 4]]
[[5 6]
 [3 7]]
Common elements between both arrays :
 [3]


In [26]:
# 3D array
arr3D=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [70]:
# continue from above....
# finding Maximum and Minimum for 3D array
print(arr3D.max())
print("index of maxValue: ",arr3D.argmax())
print(arr3D.min())
print("Sum of array elements: ", arr3D.sum())

12
index of maxValue:  11
1
Sum of array elements:  78


In [29]:
# 4D array
arr4D=np.array([[[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]], [[19,20,21],[22,23,24]]]])
print(arr4D)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]


In [71]:
# continue from above....
# finding Maximum and Minimum for 4D array
print(arr4D.max())
print("index of maxValue: ",arr4D.argmax())
print(arr4D.min())
print("index of minValue: ",arr4D.argmin())
print("Sum of array elements: ", arr4D.sum())

24
index of maxValue:  23
1
index of minValue:  0
Sum of array elements:  300


In [31]:
#.ndim(), .shape(), .size() Fn.s
# no. of dimensions, shape and size of an 2D array
print("no. of dimensions in arr2D : ",np.ndim(arr2D))  # it is a 2D array.
print("shape of arr2D : ",np.shape(arr2D)) # 2 rows and 3 columns
print("size of arr2D : ",np.size(arr2D))   # 2*3=6

no. of dimensions in arr2D :  2
shape of arr2D :  (2, 3)
size of arr2D :  6


In [26]:
# no. of dimensions, shape and size of an 3D array
print("no. of dimensions in arr3D : ",np.ndim(arr3D))  # it is a 3D array.
print("shape of arr3D : ",np.shape(arr3D)) # 2 elements+ (2 rows and 3 columns)
print("size of arr3D : ",np.size(arr3D))   # 2*2*3=12

no. of dimensions in arr3D :  3
shape of arr3D :  (2, 2, 3)
size of arr3D :  12


In [27]:
# introducing dtype
# creating array with list type float
arr=np.array([[1,2,3],[4,5,6]], dtype='float')   #dtype means Data type of element
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
#.zeros() Fn.
# Identity matrix
# creating a array with all zeros by passing tuples.
# If (a,b) passed then 2D or if (a,b,c) passed then 3D arrays will form.
arr= np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
arr= np.zeros((2,3,4)) + 5
print(arr)

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]


In [10]:
# For another identity matrix just like above
arr= np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [20]:
# For Unity metrix, where one is on main(L->R) diagonal.
# Only for 2D Matrix
arr=np.eye(4,2)
print(arr,"\n")
arr=np.eye(4)
print("In case of Square Matrix:\n",arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]] 

In case of Square Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
#.full() Fn.
# creating a constant value array of Complex type.
# If (a,b) passed then 2D or if (a,b,c) passed then 3D arrays will form.
arr=np.full((3,3), 6, dtype='complex')
print(arr)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


# STARTING OF LECTURE-26:

In [77]:
#.random.random() Fn.
# If (a,b) passed then 2D or if (a,b,c) passed then 3D arrays will form.
# all the element's value stand between 1 and 0.
# after each run values can be change.
arr=np.random.random((2,2))    
print("creating an array by given tuple with random values:\n",arr)

creating an array by given tuple with random values:
 [[0.44588125 0.00332539]
 [0.11319901 0.1707547 ]]


In [42]:
# previous example of range.
for i in range(0,31,5):
    print(i)

0
5
10
15
20
25
30


In [43]:
# .arange() Fn.
# creating a sequence of integers from 0 to 30 with step of n (here n=5) .
arr=np.arange(0,31,5)
print(arr)

[ 0  5 10 15 20 25 30]


In [57]:
# .linspace() Fn.
# creating a sequence of n (here n=10) values in range 10.5 to 15.
#then the 1st element of the array is definately 10.5 amd last one is 15.
arr=np.linspace(10.5,15,10)
print(arr)
arr=np.linspace(10,20,11)
print(arr)

[10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15. ]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [66]:
# reshape() Method of arrays
# reshaping 3X4 array to 2X2X3 array.
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("orignal array\n",arr,"\n")
newarr1=arr.reshape(2,2,3)
print("reshaped array in 2x2x3 shape\n",newarr1,"\n")
newarr2=arr.reshape(2,6)
print("reshaped array in 2x6 shape\n",newarr2,"\n")
backtofirstarr=newarr2.reshape(3,4)
print("back to orignal shape which is 3x4",backtofirstarr,"\n")

orignal array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

reshaped array in 2x2x3 shape
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

reshaped array in 2x6 shape
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

back to orignal shape which is 3x4 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [71]:
# .flatten() Method of arrays 
# ndim, size, shape attribute of arrays
# Flatten arrays.
arr2D=np.array([[1,2,3], [4,5,6]])
print("2D array\n",arr2D)
flarr2D=arr2D.flatten()
print("After flatten of 2D array, the flattered array is\n",flarr2D)
print("no. of dimensions in, shape of, size of flattered 2D array are",flarr2D.ndim,",", flarr2D.shape,",", flarr2D.size)
print("\n")
arr3D=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print("3D array\n",arr3D)
flarr3D=arr3D.flatten()
print("After flatten of 3D array, the flattered array is\n",flarr3D)
print("no. of dimensions in, shape of, size of flattered 3D array are",flarr3D.ndim,",", flarr3D.shape,",", flarr3D.size)

2D array
 [[1 2 3]
 [4 5 6]]
After flatten of 2D array, the flattered array is
 [1 2 3 4 5 6]
no. of dimensions in, shape of, size of flattered 2D array are 1 , (6,) , 6


3D array
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After flatten of 3D array, the flattered array is
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
no. of dimensions in, shape of, size of flattered 3D array are 1 , (12,) , 12


In [34]:
import numpy as np
# .random.randn() Fn. which can generate random numbers between -1 to 1.
# n for negative
Rarr=np.random.randn(2,2,2)
Rarr

array([[[-0.76099857,  1.03091789],
        [ 1.65547007, -1.47564068]],

       [[ 0.50660824,  0.66991941],
        [-1.06988474, -0.37772334]]])

In [6]:
# .random.rand() Fn.
# Before we used --> arr=np.random.random((2,2))   # here tuple is needed
# Now we are using --> 
Rarr1=np.random.rand(2,2,2)    # Difference: here, we don't need any tuple
print("Create an array of the given shape and populate it with "
      "random samples from a uniform distribution over [0, 1)\n",Rarr1,"\n")
Rarr2=np.random.rand(5)
print("in case of differente size\n",Rarr2)

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
 [[[0.58975358 0.02887122]
  [0.67784872 0.3174966 ]]

 [[0.81863998 0.25910114]
  [0.33956328 0.25922427]]] 

in case of differente size
 [0.02327304 0.39804947 0.81405564 0.22567827 0.46524339]


In [42]:
# .random.randint() Fn.
print("Generating a random integer under 10 (by default starts with 0) :")
arr=np.random.randint(10)
print(arr)
print("Generating a (by default n=1) random integer between 15 to 30 :")
arr=np.random.randint(15,30)
print(arr)
print("Generating n (here n=5) random integers between 15 to 30 :")
arr=np.random.randint(15,30,5)
print(arr)
print("Generating n (here n=10) random integers between 10 to 100 :")
arr=np.random.randint(10,100,10)
print(arr)

Generating a random integer under 10 (by default starts with 0) :
3
Generating a (by default n=1) random integer between 15 to 30 :
29
Generating n (here n=5) random integers between 15 to 30 :
[23 22 21 23 19]
Generating n (here n=10) random integers between 10 to 100 :
[41 36 71 29 91 71 48 55 14 53]


In [83]:
# .matrix() Fn.
# np.matrix Returns a matrix from an array-like object
mat1=np.matrix(np.arange(12).reshape((3,4)))  # passed argument is an array
print(mat1,"\n",type(mat1))
print("\nanother example")
mat2=np.matrix([[1,2,3], [4,5,6]])  # passed argument is also an array which is in row normal form.
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 <class 'numpy.matrix'>

another example
[[1 2 3]
 [4 5 6]]


In [72]:
# Matrix Multiplication in Python using Numpy
# Python program to demonstrate binary operators in Numpy
a=np.array([[1,2], [3,4]])
b=np.array([[4,3], [2,1]])
print("given arrays are :")
print(a)
print(b)

# Add arrays
print("Arrays Sum:\n",a+b)

# Multiply arrays (elementwise multiplication)
print("Arrays Multiplication:\n",a*b)

# Matrix Multiplication
print("Matrix Multiplication of arrays:\n",a.dot(b))
print("\n")
print("We can also perform other arithmetic operation here like : -,/,% etc.")

given arrays are :
[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
Arrays Sum:
 [[5 5]
 [5 5]]
Arrays Multiplication:
 [[4 6]
 [6 4]]
Matrix Multiplication of arrays:
 [[ 8  5]
 [20 13]]


We can also perform other arithmetic operation here like : -,/,% etc.


# Terminologies In Statistics – Statistics For Data Science

## 1) Mean :-
The mean value is the average value.The NumPy module has a method for this. Example:

In [18]:
# MEAN value
import numpy as np
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
x=np.mean(speed)
print(x)
print("%.2f" % x)

89.76923076923077
89.77


## 2) Median :-
The median value is the value in the middle, after
you have sorted all the values.

It is important that the numbers are sorted before
you can find the median.
If there are two numbers in the middle, divide the
sum of those numbers by two.
The NumPy module has a method for this. Example:

In [19]:
# MEDIAN value
import numpy as np
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]  # in Odd case 
x=np.median(speed)
print(x)
print("%.2f" % x)

numbers=[77,78,85,86,86,86,87,87,94,98,99,103]  # in Even case
y=np.median(numbers)
print(y)
print("%.2f" % y)

87.0
87.00
86.5
86.50


## 3) Mode :-
The Mode value is the value that appears the most
number of times.

Use the SciPy mode() method to find the number that
appears the most. SciPy is a free and open-source
Python library used for scientific computing and
technical computing. SciPy contains modules for
optimization, linear algebra, integration, interpolation,
special functions, signal and image processing, and
other tasks common in science and engineering. Example:

### 'Scipy'  library will use below, for finding the Mode value of given data.

In [20]:
# MODE value
from scipy import stats
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
x = stats.mode(speed)
print(x)

ModeResult(mode=array([86]), count=array([3]))


## 4) Q1,Q2,Q3 Quartiles and Interquartile Range :-
A quartile divides data into three points – a lower
quartile, median, and upper quartile – to form four
groups of the data set.

The lower quartile or first
quartile is denoted as Q1 and is the middle
number that falls between the smallest value of
the data set and the median. The second quartile,
Q2, is also the median. The upper or third quartile,
denoted as Q3, is the central point that lies
between the median and the highest number of
the distribution. Example:

In [25]:
# Q1, Q2, Q3 Quartile's values and Interquartile range(IQR)
import numpy as np
data=[ 1,3,3,4,5,6,6,7,8,8]
# First Quartile
Q1=np.median(data[:5])  # can replace 5(half of length) with int(Q2) 
print("%.2f" % Q1)
# Second Quartile
Q2=np.median(data)      
print("%.2f" % Q2)
# Third Quartile
Q3=np.median(data[5:])  # can replace 5(half of length) with int(len(data)/2)
print("%.2f" % Q3)
# Interquartile range
IQR=(Q3-Q1)
print("%.2f" % IQR)

3.00
5.50
7.00
4.00


## 5)  Standard Deviation :-
Standard deviation is a number that describes how spread out the values are. A low standard devation means that most of the numbers are close to the mean(average) value. A high standard deviation means that the values are spread out over a wider range.

Example: This time we have registered the speed of 7 cars.The NumPy module has a method for this:

In [27]:
# Standar Deviation
import numpy as np
Speed=[32,111,138,28,59,77,97]
x=np.mean(Speed)
print("Mean of Speed is %.2f" % x)
y=np.std(Speed)
print("Standar Deviation of Speed is %.2f" % y)

Mean of Speed is 77.43
Standar Deviation of Speed is 37.85
